/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedBoardRouteImport } from './routes/_authenticated/board'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCreditHistoryRouteImport } from './routes/_authenticated/credit-history'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTimeReportRouteImport } from './routes/_authenticated/time-report'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicDigestRouteImport } from './routes/api/public/digest'
import { Route as ApiPublicEmailFlushRouteImport } from './routes/api/public/email-flush'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBoardRoute = AuthenticatedBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditHistoryRoute =
  AuthenticatedCreditHistoryRouteImport.update({
    id: '/credit-history',
    path: '/credit-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimeReportRoute = AuthenticatedTimeReportRouteImport.update({
  id: '/time-report',
  path: '/time-report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDigestRoute = ApiPublicDigestRouteImport.update({
  id: '/api/public/digest',
  path: '/api/public/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailFlushRoute = ApiPublicEmailFlushRouteImport.update({
  id: '/api/public/email-flush',
  path: '/api/public/email-flush',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/board': typeof AuthenticatedBoardRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/credit-history': typeof AuthenticatedCreditHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/time-report': typeof AuthenticatedTimeReportRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/digest': typeof ApiPublicDigestRoute
  '/api/public/email-flush': typeof ApiPublicEmailFlushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/board': typeof AuthenticatedBoardRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/credit-history': typeof AuthenticatedCreditHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/time-report': typeof AuthenticatedTimeReportRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/digest': typeof ApiPublicDigestRoute
  '/api/public/email-flush': typeof ApiPublicEmailFlushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/board': typeof AuthenticatedBoardRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/credit-history': typeof AuthenticatedCreditHistoryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/time-report': typeof AuthenticatedTimeReportRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/digest': typeof ApiPublicDigestRoute
  '/api/public/email-flush': typeof ApiPublicEmailFlushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/board'
    | '/clients'
    | '/credit-history'
    | '/settings'
    | '/team'
    | '/time-report'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/digest'
    | '/api/public/email-flush'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/board'
    | '/clients'
    | '/credit-history'
    | '/settings'
    | '/team'
    | '/time-report'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/digest'
    | '/api/public/email-flush'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/board'
    | '/_authenticated/clients'
    | '/_authenticated/credit-history'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/time-report'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/digest'
    | '/api/public/email-flush'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicDigestRoute: typeof ApiPublicDigestRoute
  ApiPublicEmailFlushRoute: typeof ApiPublicEmailFlushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/board': {
      id: '/_authenticated/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AuthenticatedBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credit-history': {
      id: '/_authenticated/credit-history'
      path: '/credit-history'
      fullPath: '/credit-history'
      preLoaderRoute: typeof AuthenticatedCreditHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/time-report': {
      id: '/_authenticated/time-report'
      path: '/time-report'
      fullPath: '/time-report'
      preLoaderRoute: typeof AuthenticatedTimeReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/digest': {
      id: '/api/public/digest'
      path: '/api/public/digest'
      fullPath: '/api/public/digest'
      preLoaderRoute: typeof ApiPublicDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-flush': {
      id: '/api/public/email-flush'
      path: '/api/public/email-flush'
      fullPath: '/api/public/email-flush'
      preLoaderRoute: typeof ApiPublicEmailFlushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBoardRoute: typeof AuthenticatedBoardRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCreditHistoryRoute: typeof AuthenticatedCreditHistoryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTimeReportRoute: typeof AuthenticatedTimeReportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBoardRoute: AuthenticatedBoardRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCreditHistoryRoute: AuthenticatedCreditHistoryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTimeReportRoute: AuthenticatedTimeReportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicDigestRoute: ApiPublicDigestRoute,
  ApiPublicEmailFlushRoute: ApiPublicEmailFlushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
